version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  dbt:
    image: medicmobile/dataemon:latest
    build: .
    working_dir: /dbt/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - DATAEMON_INITAL_PACKAGE=${DATAMON_INITIAL_PACKAGE}
      - DATAEMON_INTERVAL=5
      - ROOT_POSTGRES_SCHEMA=${ROOT_POSTGRES_SCHEMA}
